const namedColors = [
  "snow",
  "snow1",
  "snow2",
  "RosyBrown1",
  "RosyBrown2",
  "snow3",
  "LightCoral",
  "IndianRed1",
  "RosyBrown3",
  "IndianRed2",
  "RosyBrown",
  "brown1",
  "firebrick1",
  "brown2",
  "IndianRed",
  "IndianRed3",
  "firebrick2",
  "snow4",
  "brown3",
  "red",
  "red1",
  "RosyBrown4",
  "firebrick3",
  "red2",
  "firebrick",
  "brown",
  "red3",
  "IndianRed4",
  "brown4",
  "firebrick4",
  "DarkRed",
  "red4",
  "maroon",
  "LightPink1",
  "LightPink3",
  "LightPink4",
  "LightPink2",
  "LightPink",
  "pink",
  "crimson",
  "pink1",
  "pink2",
  "pink3",
  "pink4",
  "PaleVioletRed4",
  "PaleVioletRed",
  "PaleVioletRed2",
  "PaleVioletRed1",
  "PaleVioletRed3",
  "LavenderBlush",
  "LavenderBlush1",
  "LavenderBlush3",
  "LavenderBlush2",
  "LavenderBlush4",
  "maroon",
  "HotPink3",
  "VioletRed3",
  "VioletRed1",
  "VioletRed2",
  "VioletRed4",
  "HotPink2",
  "HotPink1",
  "HotPink4",
  "HotPink",
  "DeepPink",
  "DeepPink1",
  "DeepPink2",
  "DeepPink3",
  "DeepPink4",
  "maroon1",
  "maroon2",
  "maroon3",
  "maroon4",
  "MediumVioletRed",
  "VioletRed",
  "orchid2",
  "orchid",
  "orchid1",
  "orchid3",
  "orchid4",
  "thistle1",
  "thistle2",
  "plum1",
  "plum2",
  "thistle",
  "thistle3",
  "plum",
  "violet",
  "plum3",
  "thistle4",
  "fuchsia",
  "magenta",
  "magenta1",
  "plum4",
  "magenta2",
  "magenta3",
  "DarkMagenta",
  "magenta4",
  "purple",
  "MediumOrchid",
  "MediumOrchid1",
  "MediumOrchid2",
  "MediumOrchid3",
  "MediumOrchid4",
  "DarkViolet",
  "DarkOrchid",
  "DarkOrchid1",
  "DarkOrchid3",
  "DarkOrchid2",
  "DarkOrchid4",
  "purple",
  "indigo",
  "BlueViolet",
  "purple2",
  "purple3",
  "purple4",
  "purple1",
  "MediumPurple",
  "MediumPurple1",
  "MediumPurple2",
  "MediumPurple3",
  "MediumPurple4",
  "DarkSlateBlue",
  "LightSlateBlue",
  "MediumSlateBlue",
  "SlateBlue",
  "SlateBlue1",
  "SlateBlue2",
  "SlateBlue3",
  "SlateBlue4",
  "GhostWhite",
  "lavender",
  "blue",
  "blue1",
  "blue2",
  "blue3",
  "MediumBlue",
  "blue4",
  "DarkBlue",
  "MidnightBlue",
  "navy",
  "NavyBlue",
  "RoyalBlue",
  "RoyalBlue1",
  "RoyalBlue2",
  "RoyalBlue3",
  "RoyalBlue4",
  "CornflowerBlue",
  "LightSteelBlue",
  "LightSteelBlue1",
  "LightSteelBlue2",
  "LightSteelBlue3",
  "LightSteelBlue4",
  "SlateGray4",
  "SlateGray1",
  "SlateGray2",
  "SlateGray3",
  "LightSlateGray",
  "LightSlateGrey",
  "SlateGray",
  "SlateGrey",
  "DodgerBlue",
  "DodgerBlue1",
  "DodgerBlue2",
  "DodgerBlue4",
  "DodgerBlue3",
  "AliceBlue",
  "SteelBlue4",
  "SteelBlue",
  "SteelBlue1",
  "SteelBlue2",
  "SteelBlue3",
  "SkyBlue4",
  "SkyBlue1",
  "SkyBlue2",
  "SkyBlue3",
  "LightSkyBlue",
  "LightSkyBlue4",
  "LightSkyBlue1",
  "LightSkyBlue2",
  "LightSkyBlue3",
  "SkyBlue",
  "LightBlue3",
  "DeepSkyBlue",
  "DeepSkyBlue1",
  "DeepSkyBlue2",
  "DeepSkyBlue4",
  "DeepSkyBlue3",
  "LightBlue1",
  "LightBlue2",
  "LightBlue",
  "LightBlue4",
  "PowderBlue",
  "CadetBlue1",
  "CadetBlue2",
  "CadetBlue3",
  "CadetBlue4",
  "turquoise1",
  "turquoise2",
  "turquoise3",
  "turquoise4",
  "cadet",
  "CadetBlue",
  "DarkTurquoise",
  "azure",
  "azure1",
  "LightCyan",
  "LightCyan1",
  "azure2",
  "LightCyan2",
  "PaleTurquoise1",
  "PaleTurquoise",
  "PaleTurquoise2",
  "DarkSlateGray1",
  "azure3",
  "LightCyan3",
  "DarkSlateGray2",
  "PaleTurquoise3",
  "DarkSlateGray3",
  "azure4",
  "LightCyan4",
  "aqua",
  "cyan",
  "cyan1",
  "PaleTurquoise4",
  "cyan2",
  "DarkSlateGray4",
  "cyan3",
  "cyan4",
  "DarkCyan",
  "teal",
  "DarkSlateGray",
  "DarkSlateGrey",
  "MediumTurquoise",
  "LightSeaGreen",
  "turquoise",
  "aquamarine4",
  "aquamarine",
  "aquamarine1",
  "aquamarine2",
  "aquamarine3",
  "MediumAquamarine",
  "MediumSpringGreen",
  "MintCream",
  "SpringGreen",
  "SpringGreen1",
  "SpringGreen2",
  "SpringGreen3",
  "SpringGreen4",
  "MediumSeaGreen",
  "SeaGreen",
  "SeaGreen3",
  "SeaGreen1",
  "SeaGreen4",
  "SeaGreen2",
  "MediumForestGreen",
  "honeydew",
  "honeydew1",
  "honeydew2",
  "DarkSeaGreen1",
  "DarkSeaGreen2",
  "PaleGreen1",
  "PaleGreen",
  "honeydew3",
  "LightGreen",
  "PaleGreen2",
  "DarkSeaGreen3",
  "DarkSeaGreen",
  "PaleGreen3",
  "honeydew4",
  "green1",
  "lime",
  "LimeGreen",
  "DarkSeaGreen4",
  "green2",
  "PaleGreen4",
  "green3",
  "ForestGreen",
  "green4",
  "green",
  "DarkGreen",
  "LawnGreen",
  "chartreuse",
  "chartreuse1",
  "chartreuse2",
  "chartreuse3",
  "chartreuse4",
  "GreenYellow",
  "DarkOliveGreen3",
  "DarkOliveGreen1",
  "DarkOliveGreen2",
  "DarkOliveGreen4",
  "DarkOliveGreen",
  "OliveDrab",
  "OliveDrab1",
  "OliveDrab2",
  "OliveDrab3",
  "YellowGreen",
  "OliveDrab4",
  "ivory",
  "ivory1",
  "LightYellow",
  "LightYellow1",
  "beige",
  "ivory2",
  "LightGoldenrodYellow",
  "LightYellow2",
  "ivory3",
  "LightYellow3",
  "ivory4",
  "LightYellow4",
  "yellow",
  "yellow1",
  "yellow2",
  "yellow3",
  "yellow4",
  "olive",
  "DarkKhaki",
  "khaki2",
  "LemonChiffon4",
  "khaki1",
  "khaki3",
  "khaki4",
  "PaleGoldenrod",
  "LemonChiffon",
  "LemonChiffon1",
  "khaki",
  "LemonChiffon3",
  "LemonChiffon2",
  "MediumGoldenRod",
  "cornsilk4",
  "gold",
  "gold1",
  "gold2",
  "gold3",
  "gold4",
  "LightGoldenrod",
  "LightGoldenrod4",
  "LightGoldenrod1",
  "LightGoldenrod3",
  "LightGoldenrod2",
  "cornsilk3",
  "cornsilk2",
  "cornsilk",
  "cornsilk1",
  "goldenrod",
  "goldenrod1",
  "goldenrod2",
  "goldenrod3",
  "goldenrod4",
  "DarkGoldenrod",
  "DarkGoldenrod1",
  "DarkGoldenrod2",
  "DarkGoldenrod3",
  "DarkGoldenrod4",
  "FloralWhite",
  "wheat2",
  "OldLace",
  "wheat",
  "wheat1",
  "wheat3",
  "orange",
  "orange1",
  "orange2",
  "orange3",
  "orange4",
  "wheat4",
  "moccasin",
  "PapayaWhip",
  "NavajoWhite3",
  "BlanchedAlmond",
  "NavajoWhite",
  "NavajoWhite1",
  "NavajoWhite2",
  "NavajoWhite4",
  "AntiqueWhite4",
  "AntiqueWhite",
  "tan",
  "bisque4",
  "burlywood",
  "AntiqueWhite2",
  "burlywood1",
  "burlywood3",
  "burlywood2",
  "AntiqueWhite1",
  "burlywood4",
  "AntiqueWhite3",
  "DarkOrange",
  "bisque2",
  "bisque",
  "bisque1",
  "bisque3",
  "DarkOrange1",
  "linen",
  "DarkOrange2",
  "DarkOrange3",
  "DarkOrange4",
  "peru",
  "tan1",
  "tan2",
  "tan3",
  "tan4",
  "PeachPuff",
  "PeachPuff1",
  "PeachPuff4",
  "PeachPuff2",
  "PeachPuff3",
  "SandyBrown",
  "seashell4",
  "seashell2",
  "seashell3",
  "chocolate",
  "chocolate1",
  "chocolate2",
  "chocolate3",
  "chocolate4",
  "SaddleBrown",
  "seashell",
  "seashell1",
  "sienna4",
  "sienna",
  "sienna1",
  "sienna2",
  "sienna3",
  "LightSalmon3",
  "LightSalmon",
  "LightSalmon1",
  "LightSalmon4",
  "LightSalmon2",
  "coral",
  "OrangeRed",
  "OrangeRed1",
  "OrangeRed2",
  "OrangeRed3",
  "OrangeRed4",
  "DarkSalmon",
  "salmon1",
  "salmon2",
  "salmon3",
  "salmon4",
  "coral1",
  "coral2",
  "coral3",
  "coral4",
  "tomato4",
  "tomato",
  "tomato1",
  "tomato2",
  "tomato3",
  "MistyRose4",
  "MistyRose2",
  "MistyRose",
  "MistyRose1",
  "salmon",
  "MistyRose3",
  "white",
  "gray100",
  "grey100",
  "grey100",
  "gray99",
  "grey99",
  "gray98",
  "grey98",
  "gray97",
  "grey97",
  "gray96",
  "grey96",
  "WhiteSmoke",
  "gray95",
  "grey95",
  "gray94",
  "grey94",
  "gray93",
  "grey93",
  "gray92",
  "grey92",
  "gray91",
  "grey91",
  "gray90",
  "grey90",
  "gray89",
  "grey89",
  "gray88",
  "grey88",
  "gray87",
  "grey87",
  "gainsboro",
  "gray86",
  "grey86",
  "gray85",
  "grey85",
  "gray84",
  "grey84",
  "gray83",
  "grey83",
  "LightGray",
  "LightGrey",
  "gray82",
  "grey82",
  "gray81",
  "grey81",
  "gray80",
  "grey80",
  "gray79",
  "grey79",
  "gray78",
  "grey78",
  "gray77",
  "grey77",
  "gray76",
  "grey76",
  "silver",
  "gray75",
  "grey75",
  "gray74",
  "grey74",
  "gray73",
  "grey73",
  "gray72",
  "grey72",
  "gray71",
  "grey71",
  "gray70",
  "grey70",
  "gray69",
  "grey69",
  "gray68",
  "grey68",
  "gray67",
  "grey67",
  "DarkGray",
  "DarkGrey",
  "gray66",
  "grey66",
  "gray65",
  "grey65",
  "gray64",
  "grey64",
  "gray63",
  "grey63",
  "gray62",
  "grey62",
  "gray61",
  "grey61",
  "gray60",
  "grey60",
  "gray59",
  "grey59",
  "gray58",
  "grey58",
  "gray57",
  "grey57",
  "gray56",
  "grey56",
  "gray55",
  "grey55",
  "gray54",
  "grey54",
  "gray53",
  "grey53",
  "gray52",
  "grey52",
  "gray51",
  "grey51",
  "fractal",
  "gray50",
  "grey50",
  "gray",
  "gray49",
  "grey49",
  "gray48",
  "grey48",
  "gray47",
  "grey47",
  "gray46",
  "grey46",
  "gray45",
  "grey45",
  "gray44",
  "grey44",
  "gray43",
  "grey43",
  "gray42",
  "grey42",
  "DimGray",
  "DimGrey",
  "gray41",
  "grey41",
  "gray40",
  "grey40",
  "gray39",
  "grey39",
  "gray38",
  "grey38",
  "gray37",
  "grey37",
  "gray36",
  "grey36",
  "gray35",
  "grey35",
  "gray34",
  "grey34",
  "gray33",
  "grey33",
  "gray32",
  "grey32",
  "gray31",
  "grey31",
  "gray30",
  "grey30",
  "gray29",
  "grey29",
  "gray28",
  "grey28",
  "gray27",
  "grey27",
  "gray26",
  "grey26",
  "gray25",
  "grey25",
  "gray24",
  "grey24",
  "gray23",
  "grey23",
  "gray22",
  "grey22",
  "gray21",
  "grey21",
  "gray20",
  "grey20",
  "gray19",
  "grey19",
  "gray18",
  "grey18",
  "gray17",
  "grey17",
  "gray16",
  "grey16",
  "gray15",
  "grey15",
  "gray14",
  "grey14",
  "gray13",
  "grey13",
  "gray12",
  "grey12",
  "gray11",
  "grey11",
  "gray10",
  "grey10",
  "gray9",
  "grey9",
  "gray8",
  "grey8",
  "gray7",
  "grey7",
  "gray6",
  "grey6",
  "gray5",
  "grey5",
  "gray4",
  "grey4",
  "gray3",
  "grey3",
  "gray2",
  "grey2",
  "gray1",
  "grey1",
  "black",
  "gray0",
  "grey0",
  "opaque",
  "none",
  "transparent",
];

const commaSeparatedGenerator = (values: Suggestion[]): Fig.Generator => ({
  script: function (context) {
    return `echo ${context[context.length - 1]}`;
  },
  postProcess: function (tokens) {
    const i = tokens.split(",").filter((d) => d).length;
    const { name, description } =
      i < values.length ? values[i] : { name: "", description: "" };
    return [{ name, description }];
  },
  trigger: ",",
  getQueryTerm: ",",
});

// Create a generator that gives suggestions for a and b when written axb
// expects numberxnumber
const axbGenerator = (a: Fig.Suggestion, b: Fig.Suggestion): Fig.Generator => ({
  script: function (context) {
    const arg = context[context.length - 1];
    if (arg.split("x").length > 1) {
      return `echo 1`;
    } else {
      return `echo 0`;
    }
  },
  postProcess: function (input) {
    if (+input) {
      return [b];
    } else {
      return [a];
    }
  },
  trigger: "x",
  getQueryTerm: "x",
});

const geometryArg = {
  name: "geometry",
  description: "",
};

const colorArg = {
  name: "color",
  description:
    "a color name, a hex color, or a numerical RGB, RGBA, HSL, HSLA, CMYK, or CMYKA specification.",
  icon: "🎨",
  suggestions: namedColors,
};

const pctArg = {
  name: "value%",
  description: "A percentage value",
};

const completionSpec: Fig.Spec = {
  name: "magick",
  description: "",
  parserDirectives: {
    flagsArePosixNoncompliant: true,
  },
  subcommands: [
    {
      name: "convert",
      args: [{ name: "Input Image", isVariadic: true, template: "filepaths" }],
      options: [
        {
          name: "-adaptive-blur",
          description:
            "adaptively blur pixels, with decreasing effect near edges.",
          args: {
            name: "radius[xsigma]",
            generators: axbGenerator(
              { name: "radius" },
              { name: "sigma", description: "defaults to 1 if not entered." }
            ),
          },
        },
        {
          name: "-adaptive-resize",
          description: "resize the image using data-dependent triangulation.",
          args: geometryArg,
        },
        {
          name: "-adaptive-sharpen",
          description:
            "adaptively sharpen pixels, with increasing effect near edges.",
          args: {
            name: "radius[xsigma]",
            generators: axbGenerator(
              { name: "radius" },
              { name: "sigma", description: "defaults to 1 if not entered." }
            ),
          },
        },
        {
          name: "-adjoin",
          description:
            "join images into a single multi-image file (enabled by default).",
        },
        {
          name: "+adjoin",
          description: "join images into a seperate signle-image files.",
        },
        {
          name: "-affine",

          description:
            "set the drawing transformation matrix for combined rotating and scaling.",
          args: {
            name: "transformation",
            generators: commaSeparatedGenerator([
              { name: "sx", description: "scale x" },
              { name: "rx", description: "shear x" },
              { name: "ry", description: "shear y" },
              { name: "sy", description: "scale y" },
              { name: "tx", description: "translate x in pixels (optional)" },
              { name: "ty", description: "translate y in pixels (optional)" },
            ]),
          },
        },
        {
          name: "-alpha",

          description: "control the alpha/matte channel of an image.",
          args: {
            name: "alpha mode",
            suggestions: [
              {
                name: "activate",
                description: "enable the transparency channel.",
              },
              {
                name: "associate",
                description: "associate the alpha channel with this image.",
              },
              {
                name: "deactivate",
                description: "disable the transparency channel.",
              },
              {
                name: "disassociate",
                description: "disassociate the alpha channel with this image.",
              },
              {
                name: "set",
                description:
                  "activate the alpha/matte channel and resets to opaque if it was previously off.",
              },
              {
                name: "opaque",
                description:
                  "enable the alpha/matte channel and forces it to be fully opaque.",
              },
              {
                name: "transparent",
                description:
                  "enable the alpha/matte channel and forces it to be fully transparent.",
              },
              {
                name: "extract",
                description:
                  "copy the alpha into all color channels and turn off the alpha channel.",
              },
              {
                name: "copy",
                description:
                  "turn on the alpha channel and copy the greyscale version of the image into it.",
              },
              {
                name: "shape",
                description: "same as copy but replace rgb with alpha shape.",
              },
              {
                name: "remove",
                description: "composite the image over the background color.",
              },
              {
                name: "remove",
                description:
                  "set any fully transparent pixel to the background color.",
              },
            ],
          },
        },
        {
          name: "-antialias",
          description:
            "enable/disable anti-aliasing pixels when drawing fonts and lines.",
        },
        {
          name: "+antialias",
          description: "disable additional of anti-aliasing edge pixels.",
        },
        { name: "-append", description: "join current images vertically." },
        { name: "+append", description: "join current images horizontall." },
        {
          name: "-attenuate",
          description: "lessen (or intensify) when adding noise to an image.",
          args: {
            name: "value",
            description:
              "if unset the value is equivalent to 1.0, or a maximum noise addition",
          },
        },
        {
          name: "-authenticate",
          description: "decrypt a PDF with a password.",
          args: {
            name: "password",
            description:
              "a password for decrypting a PDF that has been encrypted using Microsoft Crypto API (MSC API).",
          },
        },
        {
          name: "-auto-gamma",
          description: "automatically adjust the gamma level.",
        },
        {
          name: "-auto-level",
          description: "automatically adjust the color levels.",
        },
        {
          name: "-auto-orient",
          description:
            "adjusts an image so that its orientation is suitable for viewing (i.e. top-left orientation).",
        },
        {
          name: "-auto-threshold",
          description: "",
          args: {
            name: "method",
            suggestions: [
              {
                name: "undefined",
                description: "0: no method specified (equivalent to 'OTSU').",
              },
              {
                name: "kapur",
                description: "maximum entropy thresholding.",
              },
              {
                name: "otsu",
                description: "cluster-based image thresholding.",
              },
              {
                name: "triangle",
                description: "a geometric thresholding method.",
              },
            ],
          },
        },
        {
          name: "-average",
          description: "average a set of images.",
        },
        {
          name: "-backdrop",
          description: "display the image centered on a backdrop.",
        },
        {
          name: "-background",
          description: "",
          args: colorArg,
        },
        {
          name: "-bench",
          description: "measure performance",
          args: {
            name: "iterations",
            description: "number of times to repeat the benchmark.",
          },
        },
        {
          name: "-bias",
          description: "add bias when convolving an image.",
          args: pctArg,
        },
        {
          name: "-bilateral-blur",
          description:
            "a non-linear, edge-preserving, and noise-reducing smoothing filter for images.",
          args: geometryArg,
        },
        {
          name: "-black-point-compensation",
          description: "use black point compensation.",
        },
        {
          name: "-black-threshold",
          description: "",
          args: pctArg,
        },
        {
          name: "-blend",
          description:
            "blend an image into another by the given absolute value or percent.",
          args: geometryArg,
        },
        {
          name: "-blue-primary",
          description: "",
          args: { name: "x", description: "" },
        },
        {
          name: "-blue-shift",
          description: "",
          args: { name: "factor", description: "" },
        },
        {
          name: "-blur",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-border",
          description: "",
          args: geometryArg,
        },
        {
          name: "-bordercolor",
          description: "",
          args: colorArg,
        },
        {
          name: "-borderwidth",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-brightness-contrast",
          description: "",
          args: { name: "brightness", description: "" },
        },
        {
          name: "-cache",
          description: "",
          args: { name: "threshold", description: "" },
        },
        {
          name: "-canny",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-caption",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-cdl",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-channel",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-channel-fx",
          description: "",
          args: { name: "expression", description: "" },
        },
        {
          name: "-charcoal",
          description: "",
          args: { name: "factor", description: "" },
        },
        {
          name: "-chop",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-clahe",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-clamp",
          description: "",
        },
        { name: "-clip", description: "" },
        {
          name: "-clip-mask",
          description: "",
        },
        {
          name: "-clip-path",
          description: "",
          args: { name: "id", description: "" },
        },
        {
          name: "-clone",
          description: "",
          args: { name: "index(s)", description: "" },
        },
        { name: "-clut", description: "" },
        {
          name: "-coalesce",
          description: "",
        },
        {
          name: "-colorize",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-colormap",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-colors",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-color-matrix",
          description: "",
          args: { name: "matrix", description: "" },
        },
        {
          name: "-colorspace",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-color-threshold",
          description: "",
          args: { name: "start-color", description: "" },
        },
        {
          name: "-combine",
          description: "",
        },
        {
          name: "-comment",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-compare",
          description: "",
        },
        {
          name: "-complex",
          description: "",
          args: { name: "operator", description: "" },
        },
        {
          name: "-compose",
          description: "",
          args: { name: "operator", description: "" },
        },
        {
          name: "-composite",
          description: "",
        },
        {
          name: "-compress",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-connected-components",
          description: "",
          args: { name: "connectivity", description: "" },
        },
        {
          name: "-contrast",
          description: "",
        },
        {
          name: "-contrast-stretch",
          description: "",
          args: { name: "black-point", description: "" },
        },
        {
          name: "-convolve",
          description: "",
          args: { name: "kernel", description: "" },
        },
        {
          name: "-copy",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-crop",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-cycle",
          description: "",
          args: { name: "amount", description: "" },
        },
        {
          name: "-debug",
          description: "",
          args: { name: "events", description: "" },
        },
        {
          name: "-decipher",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-deconstruct",
          description: "",
        },
        {
          name: "-define",
          description: "",
          args: { name: "key", description: "" },
        },
        {
          name: "-delay",
          description: "",
          args: { name: "ticks", description: "" },
        },
        {
          name: "-delete",
          description: "",
          args: { name: "indexes", description: "" },
        },
        {
          name: "-density",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-depth",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-descend",
          description: "",
        },
        {
          name: "-deskew",
          description: "",
          args: { name: "threshold{%}", description: "" },
        },
        {
          name: "-despeckle",
          description: "",
        },
        {
          name: "-direction",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-displace",
          description: "",
          args: { name: "horizontal-scale", description: "" },
        },
        {
          name: "-display",
          description: "",
          args: { name: "host:display[.screen]", description: "" },
        },
        {
          name: "-dispose",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-dissimilarity-threshold",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-dissolve",
          description: "",
          args: { name: "src_percent", description: "" },
        },
        {
          name: "-distort",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-distribute-cache",
          description: "",
          args: { name: "port", description: "" },
        },
        {
          name: "-dither",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-draw",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-duplicate",
          description: "",
          args: { name: "count,indexes", description: "" },
        },
        {
          name: "-edge",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-emboss",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-encipher",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-encoding",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-endian",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-enhance",
          description: "",
        },
        {
          name: "-equalize",
          description: "",
        },
        {
          name: "-evaluate",
          description: "",
          args: { name: "operator", description: "" },
        },
        {
          name: "-evaluate-sequence",
          description: "",
          args: { name: "operator", description: "" },
        },
        {
          name: "-extent",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-extract",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-family",
          description: "",
          args: { name: "fontFamily", description: "" },
        },
        {
          name: "-features",
          description: "",
          args: { name: "distance", description: "" },
        },
        { name: "-fft", description: "" },
        {
          name: "-fill",
          description: "",
          args: colorArg,
        },
        {
          name: "-filter",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-flatten",
          description: "",
        },
        { name: "-flip", description: "" },
        {
          name: "-floodfill",
          description: "",
          args: { name: "{", description: "" },
        },
        { name: "-flop", description: "" },
        {
          name: "-font",
          description: "",
          args: { name: "name", description: "" },
        },
        {
          name: "-foreground",
          description: "",
          args: colorArg,
        },
        {
          name: "-format",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-frame",
          description: "",
        },
        {
          name: "-function",
          description: "",
          args: { name: "function", description: "" },
        },
        {
          name: "-fuzz",
          description: "",
          args: { name: "distance", description: "" },
        },
        {
          name: "-fx",
          description: "",
          args: { name: "expression", description: "" },
        },
        {
          name: "-gamma",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-gaussian-blur",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-geometry",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-gravity",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-grayscale",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-green-primary",
          description: "",
          args: { name: "x,y", description: "" },
        },
        {
          name: "-hald-clut",
          description: "",
        },
        { name: "-help", description: "" },
        {
          name: "-highlight-color",
          description: "",
          args: colorArg,
        },
        {
          name: "-hough-lines",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-iconGeometry",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-iconic",
          description: "",
        },
        {
          name: "-identify",
          description: "",
        },
        { name: "-ift", description: "" },
        {
          name: "-illuminant",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-immutable",
          description: "",
        },
        {
          name: "-implode",
          description: "",
          args: { name: "factor", description: "" },
        },
        {
          name: "-insert",
          description: "",
          args: { name: "index", description: "" },
        },
        {
          name: "-intensity",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-intent",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-interlace",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-interline-spacing",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-interpolate",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-interpolative-resize",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-interword-spacing",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-kerning",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-kmeans",
          description: "",
          args: { name: "colors", description: "" },
        },
        {
          name: "-kuwahara",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-label",
          description: "",
          args: { name: "name", description: "" },
        },
        {
          name: "-lat",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-layers",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-level",
          description: "",
          args: { name: "black_point", description: "" },
        },
        {
          name: "-level-colors",
          description: "",
          args: { name: "{", description: "" },
        },
        {
          name: "-limit",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-linear-stretch",
          description: "",
          args: { name: "black-point", description: "" },
        },
        {
          name: "-linewidth",
          description: "",
        },
        {
          name: "-liquid-rescale",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-list",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-log",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-loop",
          description: "",
          args: { name: "iterations", description: "" },
        },
        {
          name: "-lowlight-color",
          description: "",
          args: colorArg,
        },
        {
          name: "-magnify",
          description: "",
        },
        {
          name: "-map",
          description: "",
          args: { name: "components", description: "" },
        },
        {
          name: "-mattecolor",
          description: "",
          args: colorArg,
        },
        {
          name: "-maximum",
          description: "",
        },
        {
          name: "-median",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-mean-shift",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-metric",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-minimum",
          description: "",
        },
        {
          name: "-mode",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-modulate",
          description: "",
          args: { name: "brightness", description: "" },
        },
        {
          name: "-moments",
          description: "",
        },
        {
          name: "-monitor",
          description: "",
        },
        {
          name: "-monochrome",
          description: "",
        },
        {
          name: "-morph",
          description: "",
          args: { name: "frames", description: "" },
        },
        {
          name: "-morphology",
          description: "",
        },
        {
          name: "kernel",
          description: "",
        },
        {
          name: "-mosaic",
          description: "",
        },
        {
          name: "-motion-blur",
          description: "",
          args: { name: "radius", description: "" },
        },
        { name: "-name", description: "" },
        {
          name: "-negate",
          description: "",
        },
        {
          name: "-noise",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-normalize",
          description: "",
        },
        {
          name: "-opaque",
          description: "",
          args: colorArg,
        },
        {
          name: "-ordered-dither",
          description: "",
          args: { name: "threshold_map", description: "" },
        },
        {
          name: "-orient",
          description: "",
          args: { name: "image", description: "" },
        },
        {
          name: "-page",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-paint",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-path",
          description: "",
          args: { name: "path", description: "" },
        },
        {
          name: "-pause",
          description: "",
          args: { name: "seconds", description: "" },
        },
        {
          name: "-perceptible",
          description: "",
          args: { name: "epsilon", description: "" },
        },
        { name: "-ping", description: "" },
        {
          name: "-pointsize",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-polaroid",
          description: "",
          args: { name: "angle", description: "" },
        },

        {
          name: "-poly",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-posterize",
          description: "",
          args: { name: "levels", description: "" },
        },
        {
          name: "-precision",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-preview",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-print",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-process",
          description: "",
          args: { name: "command", description: "" },
        },
        {
          name: "-profile",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-quality",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-quantize",
          description: "",
          args: { name: "colorspace", description: "" },
        },
        {
          name: "-quiet",
          description: "",
        },
        {
          name: "-radial-blur",
          description: "",
          args: { name: "angle", description: "" },
        },
        {
          name: "-raise",
          description: "",
          args: { name: "thickness", description: "" },
        },
        {
          name: "-random-threshold",
          description: "",
          args: { name: "low", description: "" },
        },
        {
          name: "-range-threshold",
          description: "",
          args: { name: "low-black", description: "" },
        },
        {
          name: "-read-mask",
          description: "",
        },
        {
          name: "-red-primary",
          description: "",
          args: { name: "x,y", description: "" },
        },
        {
          name: "-regard-warnings",
          description: "",
        },
        {
          name: "-remap",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-region",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-remote",
          description: "",
        },
        {
          name: "-render",
          description: "",
        },
        {
          name: "-repage",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-resample",
          description: "",
          args: { name: "horizontal", description: "" },
        },
        {
          name: "-resize",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-respect-parentheses",
          description: "",
        },
        {
          name: "-reverse",
          description: "",
        },
        {
          name: "-roll",
          description: "",
          args: { name: "{", description: "" },
        },
        {
          name: "-rotate",
          description: "",
          args: { name: "degrees", description: "" },
        },
        {
          name: "-sample",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-sampling-factor",
          description: "",
          args: { name: "horizontal-factor", description: "" },
        },
        {
          name: "-scale",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-scene",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-screen",
          description: "",
        },
        { name: "-seed", description: "" },
        {
          name: "-segment",
          description: "",
          args: { name: "cluster-threshold", description: "" },
        },
        {
          name: "-selective-blur",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-separate",
          description: "",
        },
        {
          name: "-sepia-tone",
          description: "",
          args: { name: "percent-threshold", description: "" },
        },
        {
          name: "-set",
          description: "",
          args: { name: "key", description: "" },
        },
        {
          name: "-shade",
          description: "",
          args: { name: "azimuth", description: "" },
        },
        {
          name: "-shadow",
          description: "",
          args: { name: "percent-opacity", description: "" },
        },
        {
          name: "-sharpen",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-shave",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-shear",
          description: "",
          args: { name: "Xdegrees", description: "" },
        },
        {
          name: "-sigmoidal-contrast",
          description: "",
          args: { name: "contrast", description: "" },
        },
        {
          name: "-silent",
          description: "",
        },
        {
          name: "-similarity-threshold",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-size",
          description: "",
          args: { name: "width", description: "" },
        },
        {
          name: "-sketch",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-smush",
          description: "",
          args: { name: "offset", description: "" },
        },
        {
          name: "-snaps",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-solarize",
          description: "",
          args: { name: "percent-threshold", description: "" },
        },
        {
          name: "-sort-pixels",
          description: "",
        },
        {
          name: "-sparse-color",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-splice",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-spread",
          description: "",
          args: { name: "amount", description: "" },
        },
        {
          name: "-statistic",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-stegano",
          description: "",
          args: { name: "offset", description: "" },
        },
        {
          name: "-stereo",
          description: "",
          args: { name: "+x", description: "" },
        },
        {
          name: "-storage-type",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-stretch",
          description: "",
          args: { name: "fontStretch", description: "" },
        },
        {
          name: "-strip",
          description: "",
        },
        {
          name: "-stroke",
          description: "",
          args: colorArg,
        },
        {
          name: "-strokewidth",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-style",
          description: "",
          args: { name: "fontStyle", description: "" },
        },
        {
          name: "-subimage-search",
          description: "",
        },
        {
          name: "-swap",
          description: "",
          args: { name: "index,index", description: "" },
        },
        {
          name: "-swirl",
          description: "",
          args: { name: "degrees", description: "" },
        },
        {
          name: "-synchronize",
          description: "",
        },
        {
          name: "-taint",
          description: "",
        },
        {
          name: "-text-font",
          description: "",
          args: { name: "name", description: "" },
        },
        {
          name: "-texture",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-threshold",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-thumbnail",
          description: "",
          args: { name: "geometry", description: "" },
        },
        {
          name: "-tile",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-tile-offset",
          description: "",
          args: { name: "{", description: "" },
        },
        {
          name: "-tint",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-title",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-transform",
          description: "",
        },
        {
          name: "-transparent",
          description: "",
          args: colorArg,
        },
        {
          name: "-transparent-color",
          description: "",
          args: colorArg,
        },
        {
          name: "-transpose",
          description: "",
        },
        {
          name: "-transverse",
          description: "",
        },
        {
          name: "-treedepth",
          description: "",
          args: { name: "value", description: "" },
        },
        { name: "-trim", description: "" },
        {
          name: "-type",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-undercolor",
          description: "",
          args: colorArg,
        },
        {
          name: "-update",
          description: "",
          args: { name: "seconds", description: "" },
        },
        {
          name: "-unique-colors",
          description: "",
        },
        {
          name: "-units",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-unsharp",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-verbose",
          description: "",
        },
        {
          name: "-version",
          description: "",
        },
        {
          name: "-view",
          description: "",
          args: { name: "string", description: "" },
        },
        {
          name: "-vignette",
          description: "",
          args: { name: "radius", description: "" },
        },
        {
          name: "-virtual-pixel",
          description: "",
          args: { name: "method", description: "" },
        },
        {
          name: "-visual",
          description: "",
          args: { name: "type", description: "" },
        },
        {
          name: "-watermark",
          description: "",
          args: { name: "brightness", description: "" },
        },
        {
          name: "-wave",
          description: "",
          args: { name: "amplitude", description: "" },
        },
        {
          name: "-wavelet-denoise",
          description: "",
          args: { name: "threshold", description: "" },
        },
        {
          name: "-weight",
          description: "",
          args: { name: "fontWeight", description: "" },
        },
        {
          name: "-white-balance",
          description: "",
        },
        {
          name: "-white-point",
          description: "",
          args: { name: "x,y", description: "" },
        },
        {
          name: "-white-threshold",
          description: "",
          args: { name: "value", description: "" },
        },
        {
          name: "-window",
          description: "",
          args: { name: "id", description: "" },
        },
        {
          name: "-window-group",
          description: "",
        },
        {
          name: "-write",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
        {
          name: "-write-mask",
          description: "",
          args: { name: "filename", template: "filepaths" },
        },
      ],
    },
  ],

  // Only uncomment if magick takes an argument
  // args: {}
};

export default completionSpec;
